# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	# Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = "packer-built"
	config.vm.box_url = "../packer/build/ubuntu-16.04-amd64.box"	

end
